#!/bin/bash
#Engineer: T Looby
#Date: 06/28/2022
#Description:  prepares docker context, then creates docker container
#              from dev machine

# remove previous build
rm -rf dockerDir

# make new docker staging directory for docker context
mkdir -p dockerDir/docker
mkdir -p dockerDir/source/reduced2DCAD/

# copy dockerfile, recipes, bash scripts
cp -n buildDocker dockerDir/docker
cp -n docker-compose.yml dockerDir/docker
cp -n Dockerfile dockerDir/docker
cp -n runDockerCompose dockerDir/docker
cp -n github/requirements.txt dockerDir/docker

# copy code into the AppDir
rm -rf /home/tom/source/reduced2DCAD/github/docker
#copy CADClass and toolsClass (will fail if they are already linked)
cp -r /home/tom/source/HEAT/github/source/CADClass.py /home/tom/source/reduced2DCAD/github/
cp -r /home/tom/source/HEAT/github/source/toolsClass.py /home/tom/source/reduced2DCAD/github/
cp -r /home/tom/source/reduced2DCAD/github/*  dockerDir/source/reduced2DCAD/

#copy docker files to reduced2DCAD rootDir for uploading to github
#this clobbers old files
# copy dockerfile, recipes, bash scripts
mkdir -p /home/tom/source/reduced2DCAD/github/docker
cp buildDocker /home/tom/source/reduced2DCAD/github/docker/
cp docker-compose.yml /home/tom/source/reduced2DCAD/github/docker/
cp Dockerfile /home/tom/source/reduced2DCAD/github/docker/
cp runDockerCompose /home/tom/source/reduced2DCAD/github/docker/


#run docker build command
echo "Building docker image..."
cd dockerDir/docker

docker build -t plasmapotential/reduced2dcad .

#after creating image, tag it using the following command
# docker tag plasmapotential/reduced2dcad:latest plasmapotential/reduced2dcad:<tag>
#
#upload to dockerhub via the following command
# docker push plasmapotential/reduced2DCAD:<tag>
#
