#docker-compose.yml
#Engineer:  T. Looby
#Date: 20220124
#Description: Docker recipe for development.  Generates environment.
#             requires user to have the volumes below locally on host
#             if not, comment out the line for the dir you don't have
#             if so, change paths to match your machine
version: "3"

services:
  reduced2DCAD:
    image: "plasmapotential/reduced2dcad"
    ports:
      - "8050:8050"
    volumes:
      #change volumes below to match your development (host) machine
      #format is: /host/path:/container/path
      #user should not edit container paths
      #options for windows and linux below
      #
      #
#      # === FOR Devon's Mac ===
#      # reduced2DCAD source code from github
#       - /Users/dbattaglia@cfs.energy/Documents/reduced2DCAD/reduced2DCAD:/root/source/reduced2DCAD
#      # files dir
#       - /Users/dbattaglia@cfs.energy/Documents/reduced2DCAD/CAD_files:/root/files
#
      # === FOR Tom's LINUX ===
      # reduced2DCAD source code from github
       - /home/tom/source/reduced2DCAD/github:/root/source/reduced2DCAD
      # files dir
       - /home/tom/work/CFS/projects/reducedCAD:/root/files
#
#      # === FOR Tom's WINDOWS ===
#      # CADtools source code from github
#       - C:\Users\tlooby\github\reduced2DCAD:/root/source/reduced2DCAD
#      # files directory
#       - C:\Users\tlooby\SPARC\2DreducedCAD:/root/files

    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #if you want to set env vars, do it here:
    environment:
    - dockerUID=$dockerUID
    - dockerGID=$dockerGID
    - runMode=docker



#NOTES:
#to run HEAT in batch mode, first bind mount the /root/terminal directory to your
#local directory with the batchFile, then run:
# python3 launchHEAT.py --m t --f /root/terminal/batchFile.dat
#
#to run an interactive shell use this command:
# docker-compose run HEAT /bin/bash
#
# to change image tag name:
# docker tag plasmapotential/heat:latest plasmapotential/heat:<tag>
